spring:
  application:
    name: Gateway-Service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v1/users/**
          filters:
            - AuthFilter

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/v1/products/**
          filters:
            - AuthFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/v1/auth/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/v1/products/**
          filters:
            - AuthFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080